# render.yaml

services:
  - type: web
    name: budzet_domowy
    env: python
    plan: free  # Możesz wybrać darmowy plan
    region: Poland  # Lub inny dostępny region
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn budzet_domowy.wsgi --log-file -"
    autoDeploy: true
    repo: "AdamczewskiDev/budzet_domowy"  # Podaj nazwę swojego repozytorium w formacie konto/repozytorium
    branch: main  # Główna gałąź do wdrożenia
    healthCheckPath: "/"
    envVars:
      - key: DJANGO_SECRET_KEY
        sync: false  # Można ustawić na true, aby aktualizować klucz przy zmianie
        value: "0v$$vq4k+^-958!1b5zcmo4s$l7nmwq5+w&-op5lqj0"  # Wprowadź swój klucz lub dodaj go w ustawieniach Rendera
      - key: DATABASE_URL
        fromDatabase:
          name: budzet_domowy_db  # Nazwa usługi bazy danych na Renderze (jeśli już istnieje)

databases:
  - name: budzet_domowy_db
    plan: free
    region: Poland  # Region powinien być taki sam jak region web service
    databaseName: budzet_domowy
